package com.epic.pos.posApp.Mapping;
// Generated Aug 13, 2019 3:05:22 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Complaincategory generated by hbm2java
 */
@Entity
@Table(name="complaincategory"
)
public class Complaincategory  implements java.io.Serializable {


     private String categorycode;
     private Status status;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Complaintype> complaintypes = new HashSet<Complaintype>(0);

    public Complaincategory() {
    }

	
    public Complaincategory(String categorycode, Status status, Date lastupdatedtime, Date createdtime) {
        this.categorycode = categorycode;
        this.status = status;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Complaincategory(String categorycode, Status status, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Complaintype> complaintypes) {
       this.categorycode = categorycode;
       this.status = status;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.complaintypes = complaintypes;
    }
   
     @Id

    
    @Column(name="CATEGORYCODE", unique=true, nullable=false, length=16)
    public String getCategorycode() {
        return this.categorycode;
    }
    
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="complaincategory")
    public Set<Complaintype> getComplaintypes() {
        return this.complaintypes;
    }
    
    public void setComplaintypes(Set<Complaintype> complaintypes) {
        this.complaintypes = complaintypes;
    }




}


