package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Statuscategory generated by hbm2java
 */
@Entity
@Table(name="statuscategory"
)
public class Statuscategory  implements java.io.Serializable {


     private String statuscategorycode;
     private String description;
     private Set<Status> statuses = new HashSet<Status>(0);

    public Statuscategory() {
    }

	
    public Statuscategory(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }
    public Statuscategory(String statuscategorycode, String description, Set<Status> statuses) {
       this.statuscategorycode = statuscategorycode;
       this.description = description;
       this.statuses = statuses;
    }
   
     @Id

    
    @Column(name="STATUSCATEGORYCODE", unique=true, nullable=false, length=16)
    public String getStatuscategorycode() {
        return this.statuscategorycode;
    }
    
    public void setStatuscategorycode(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statuscategory")
    public Set<Status> getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set<Status> statuses) {
        this.statuses = statuses;
    }




}


