package com.epic.pos.posApp.Mapping;
// Generated Sep 10, 2019 2:47:47 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Terminal generated by hbm2java
 */
@Entity
@Table(name="terminal"
)
public class Terminal  implements java.io.Serializable {


     private Long id;
     private Bank bank;
     private Currency currency;
     private Device device;
     private Merchant merchant;
     private Status status;
     private String terminalid;
     private String sheremerchantid;
     private Boolean ismaster;
     private Short sortkey;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Terminal() {
    }

	
    public Terminal(Bank bank, Currency currency, Device device, Merchant merchant, String terminalid, Date lastupdatedtime, Date createdtime) {
        this.bank = bank;
        this.currency = currency;
        this.device = device;
        this.merchant = merchant;
        this.terminalid = terminalid;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Terminal(Bank bank, Currency currency, Device device, Merchant merchant, Status status, String terminalid, String sheremerchantid, Boolean ismaster, Short sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.bank = bank;
       this.currency = currency;
       this.device = device;
       this.merchant = merchant;
       this.status = status;
       this.terminalid = terminalid;
       this.sheremerchantid = sheremerchantid;
       this.ismaster = ismaster;
       this.sortkey = sortkey;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BANK", nullable=false)
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURRENCY", nullable=false)
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEVICE", nullable=false)
    public Device getDevice() {
        return this.device;
    }
    
    public void setDevice(Device device) {
        this.device = device;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MERCHANT", nullable=false)
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="TERMINALID", nullable=false, length=8)
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }

    
    @Column(name="SHEREMERCHANTID", length=15)
    public String getSheremerchantid() {
        return this.sheremerchantid;
    }
    
    public void setSheremerchantid(String sheremerchantid) {
        this.sheremerchantid = sheremerchantid;
    }

    
    @Column(name="ISMASTER")
    public Boolean getIsmaster() {
        return this.ismaster;
    }
    
    public void setIsmaster(Boolean ismaster) {
        this.ismaster = ismaster;
    }

    
    @Column(name="SORTKEY")
    public Short getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Short sortkey) {
        this.sortkey = sortkey;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


