package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Pageuserrole generated by hbm2java
 */
@Entity
@Table(name="pageuserrole"
)
public class Pageuserrole  implements java.io.Serializable {


     private PageuserroleId id;
     private Page page;
     private Userrole userrole;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Pageuserrole() {
    }

	
    public Pageuserrole(PageuserroleId id, Page page, Userrole userrole, Date lastupdatedtime, Date createdtime) {
        this.id = id;
        this.page = page;
        this.userrole = userrole;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Pageuserrole(PageuserroleId id, Page page, Userrole userrole, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.page = page;
       this.userrole = userrole;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="page", column=@Column(name="PAGE", nullable=false, length=16) ),
        @AttributeOverride(name="userrole", column=@Column(name="USERROLE", nullable=false) ) } )
    public PageuserroleId getId() {
        return this.id;
    }
    
    public void setId(PageuserroleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGE", nullable=false, insertable=false, updatable=false)
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE", nullable=false, insertable=false, updatable=false)
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


