package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name="section"
)
public class Section  implements java.io.Serializable {


     private String sectioncode;
     private String description;
     private Set<Page> pages = new HashSet<Page>(0);

    public Section() {
    }

	
    public Section(String sectioncode, String description) {
        this.sectioncode = sectioncode;
        this.description = description;
    }
    public Section(String sectioncode, String description, Set<Page> pages) {
       this.sectioncode = sectioncode;
       this.description = description;
       this.pages = pages;
    }
   
     @Id

    
    @Column(name="SECTIONCODE", unique=true, nullable=false, length=16)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="section")
    public Set<Page> getPages() {
        return this.pages;
    }
    
    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }




}


