package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
)
public class Task  implements java.io.Serializable {


     private String taskcode;
     private String description;
     private Set<Pagetask> pagetasks = new HashSet<Pagetask>(0);
     private Set<Pagetaskuserrole> pagetaskuserroles = new HashSet<Pagetaskuserrole>(0);
     private Set<Tmpauthrec> tmpauthrecs = new HashSet<Tmpauthrec>(0);

    public Task() {
    }

	
    public Task(String taskcode) {
        this.taskcode = taskcode;
    }
    public Task(String taskcode, String description, Set<Pagetask> pagetasks, Set<Pagetaskuserrole> pagetaskuserroles, Set<Tmpauthrec> tmpauthrecs) {
       this.taskcode = taskcode;
       this.description = description;
       this.pagetasks = pagetasks;
       this.pagetaskuserroles = pagetaskuserroles;
       this.tmpauthrecs = tmpauthrecs;
    }
   
     @Id

    
    @Column(name="TASKCODE", unique=true, nullable=false, length=16)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="task")
    public Set<Pagetask> getPagetasks() {
        return this.pagetasks;
    }
    
    public void setPagetasks(Set<Pagetask> pagetasks) {
        this.pagetasks = pagetasks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="task")
    public Set<Pagetaskuserrole> getPagetaskuserroles() {
        return this.pagetaskuserroles;
    }
    
    public void setPagetaskuserroles(Set<Pagetaskuserrole> pagetaskuserroles) {
        this.pagetaskuserroles = pagetaskuserroles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="task")
    public Set<Tmpauthrec> getTmpauthrecs() {
        return this.tmpauthrecs;
    }
    
    public void setTmpauthrecs(Set<Tmpauthrec> tmpauthrecs) {
        this.tmpauthrecs = tmpauthrecs;
    }




}


