package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name="application"
)
public class Application  implements java.io.Serializable {


     private Integer id;
     private Institute institute;
     private Status status;
     private String appcode;
     private String description;
     private String configurl;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Date createdtime;
     private Set<Applicationversion> applicationversions = new HashSet<Applicationversion>(0);

    public Application() {
    }

	
    public Application(Institute institute, Status status, String appcode, Date lastupdatedtime, Date createdtime) {
        this.institute = institute;
        this.status = status;
        this.appcode = appcode;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Application(Institute institute, Status status, String appcode, String description, String configurl, Date lastupdatedtime, String lastupdateduser, Date createdtime, Set<Applicationversion> applicationversions) {
       this.institute = institute;
       this.status = status;
       this.appcode = appcode;
       this.description = description;
       this.configurl = configurl;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.createdtime = createdtime;
       this.applicationversions = applicationversions;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSTITUTE", nullable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="APPCODE", nullable=false, length=16)
    public String getAppcode() {
        return this.appcode;
    }
    
    public void setAppcode(String appcode) {
        this.appcode = appcode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="CONFIGURL", length=256)
    public String getConfigurl() {
        return this.configurl;
    }
    
    public void setConfigurl(String configurl) {
        this.configurl = configurl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="application")
    public Set<Applicationversion> getApplicationversions() {
        return this.applicationversions;
    }
    
    public void setApplicationversions(Set<Applicationversion> applicationversions) {
        this.applicationversions = applicationversions;
    }




}


