package com.epic.pos.posApp.Mapping;
// Generated Sep 30, 2019 11:18:08 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Colors generated by hbm2java
 */
@Entity
@Table(name="colors"
)
public class Colors  implements java.io.Serializable {


     private Integer id;
     private Status status;
     private String color;

    public Colors() {
    }

	
    public Colors(Status status) {
        this.status = status;
    }
    public Colors(Status status, String color) {
       this.status = status;
       this.color = color;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="COLOR", length=128)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


