package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
)
public class District  implements java.io.Serializable {


     private String districtcode;
     private Province province;
     private Status status;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<City> cities = new HashSet<City>(0);
     private Set<Merchant> merchants = new HashSet<Merchant>(0);
     private Set<Merchantcustomer> merchantcustomers = new HashSet<Merchantcustomer>(0);

    public District() {
    }

	
    public District(String districtcode, Province province, Status status, String description, Date lastupdatedtime, Date createdtime) {
        this.districtcode = districtcode;
        this.province = province;
        this.status = status;
        this.description = description;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public District(String districtcode, Province province, Status status, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<City> cities, Set<Merchant> merchants, Set<Merchantcustomer> merchantcustomers) {
       this.districtcode = districtcode;
       this.province = province;
       this.status = status;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.cities = cities;
       this.merchants = merchants;
       this.merchantcustomers = merchantcustomers;
    }
   
     @Id

    
    @Column(name="DISTRICTCODE", unique=true, nullable=false, length=16)
    public String getDistrictcode() {
        return this.districtcode;
    }
    
    public void setDistrictcode(String districtcode) {
        this.districtcode = districtcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROVINCE", nullable=false)
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<Merchantcustomer> getMerchantcustomers() {
        return this.merchantcustomers;
    }
    
    public void setMerchantcustomers(Set<Merchantcustomer> merchantcustomers) {
        this.merchantcustomers = merchantcustomers;
    }




}


