package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Passwordparm generated by hbm2java
 */
@Entity
@Table(name="passwordparm"
)
public class Passwordparm  implements java.io.Serializable {


     private String paramcode;
     private String description;
     private String value;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Passwordparm() {
    }

	
    public Passwordparm(String paramcode, String description, Date lastupdatedtime, Date createdtime) {
        this.paramcode = paramcode;
        this.description = description;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Passwordparm(String paramcode, String description, String value, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.paramcode = paramcode;
       this.description = description;
       this.value = value;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id

    
    @Column(name="PARAMCODE", unique=true, nullable=false, length=16)
    public String getParamcode() {
        return this.paramcode;
    }
    
    public void setParamcode(String paramcode) {
        this.paramcode = paramcode;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="VALUE", length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


