package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tmpauthrec generated by hbm2java
 */
@Entity
@Table(name="tmpauthrec"
)
public class Tmpauthrec  implements java.io.Serializable {


     private Integer id;
     private Instance instance;
     private Institute institute;
     private Page page;
     private Status status;
     private Task task;
     private String key1;
     private String key2;
     private String key3;
     private String key4;
     private String key5;
     private String key6;
     private String key7;
     private String key8;
     private String key9;
     private String key10;
     private String key11;
     private String key12;
     private String key13;
     private String key14;
     private String key15;
     private String key16;
     private String key17;
     private String key18;
     private String key19;
     private String key20;
     private String key21;
     private String key22;
     private String key23;
     private String key24;
     private String key25;
     private byte[] blob1;
     private byte[] blob2;
     private String tmprecord;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Tmpauthrec() {
    }

	
    public Tmpauthrec(Instance instance, Page page, Status status, Task task, Date lastupdatedtime, Date createdtime) {
        this.instance = instance;
        this.page = page;
        this.status = status;
        this.task = task;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Tmpauthrec(Instance instance, Institute institute, Page page, Status status, Task task, String key1, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9, String key10, String key11, String key12, String key13, String key14, String key15, String key16, String key17, String key18, String key19, String key20, String key21, String key22, String key23, String key24, String key25, byte[] blob1, byte[] blob2, String tmprecord, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.instance = instance;
       this.institute = institute;
       this.page = page;
       this.status = status;
       this.task = task;
       this.key1 = key1;
       this.key2 = key2;
       this.key3 = key3;
       this.key4 = key4;
       this.key5 = key5;
       this.key6 = key6;
       this.key7 = key7;
       this.key8 = key8;
       this.key9 = key9;
       this.key10 = key10;
       this.key11 = key11;
       this.key12 = key12;
       this.key13 = key13;
       this.key14 = key14;
       this.key15 = key15;
       this.key16 = key16;
       this.key17 = key17;
       this.key18 = key18;
       this.key19 = key19;
       this.key20 = key20;
       this.key21 = key21;
       this.key22 = key22;
       this.key23 = key23;
       this.key24 = key24;
       this.key25 = key25;
       this.blob1 = blob1;
       this.blob2 = blob2;
       this.tmprecord = tmprecord;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSTANCE", nullable=false)
    public Instance getInstance() {
        return this.instance;
    }
    
    public void setInstance(Instance instance) {
        this.instance = instance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSTITUTE")
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGE", nullable=false)
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TASK", nullable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

    
    @Column(name="KEY1", length=64)
    public String getKey1() {
        return this.key1;
    }
    
    public void setKey1(String key1) {
        this.key1 = key1;
    }

    
    @Column(name="KEY2", length=64)
    public String getKey2() {
        return this.key2;
    }
    
    public void setKey2(String key2) {
        this.key2 = key2;
    }

    
    @Column(name="KEY3", length=64)
    public String getKey3() {
        return this.key3;
    }
    
    public void setKey3(String key3) {
        this.key3 = key3;
    }

    
    @Column(name="KEY4", length=64)
    public String getKey4() {
        return this.key4;
    }
    
    public void setKey4(String key4) {
        this.key4 = key4;
    }

    
    @Column(name="KEY5", length=64)
    public String getKey5() {
        return this.key5;
    }
    
    public void setKey5(String key5) {
        this.key5 = key5;
    }

    
    @Column(name="KEY6", length=64)
    public String getKey6() {
        return this.key6;
    }
    
    public void setKey6(String key6) {
        this.key6 = key6;
    }

    
    @Column(name="KEY7", length=64)
    public String getKey7() {
        return this.key7;
    }
    
    public void setKey7(String key7) {
        this.key7 = key7;
    }

    
    @Column(name="KEY8", length=64)
    public String getKey8() {
        return this.key8;
    }
    
    public void setKey8(String key8) {
        this.key8 = key8;
    }

    
    @Column(name="KEY9", length=64)
    public String getKey9() {
        return this.key9;
    }
    
    public void setKey9(String key9) {
        this.key9 = key9;
    }

    
    @Column(name="KEY10", length=64)
    public String getKey10() {
        return this.key10;
    }
    
    public void setKey10(String key10) {
        this.key10 = key10;
    }

    
    @Column(name="KEY11", length=64)
    public String getKey11() {
        return this.key11;
    }
    
    public void setKey11(String key11) {
        this.key11 = key11;
    }

    
    @Column(name="KEY12", length=64)
    public String getKey12() {
        return this.key12;
    }
    
    public void setKey12(String key12) {
        this.key12 = key12;
    }

    
    @Column(name="KEY13", length=64)
    public String getKey13() {
        return this.key13;
    }
    
    public void setKey13(String key13) {
        this.key13 = key13;
    }

    
    @Column(name="KEY14", length=64)
    public String getKey14() {
        return this.key14;
    }
    
    public void setKey14(String key14) {
        this.key14 = key14;
    }

    
    @Column(name="KEY15", length=64)
    public String getKey15() {
        return this.key15;
    }
    
    public void setKey15(String key15) {
        this.key15 = key15;
    }

    
    @Column(name="KEY16", length=64)
    public String getKey16() {
        return this.key16;
    }
    
    public void setKey16(String key16) {
        this.key16 = key16;
    }

    
    @Column(name="KEY17", length=64)
    public String getKey17() {
        return this.key17;
    }
    
    public void setKey17(String key17) {
        this.key17 = key17;
    }

    
    @Column(name="KEY18", length=64)
    public String getKey18() {
        return this.key18;
    }
    
    public void setKey18(String key18) {
        this.key18 = key18;
    }

    
    @Column(name="KEY19", length=64)
    public String getKey19() {
        return this.key19;
    }
    
    public void setKey19(String key19) {
        this.key19 = key19;
    }

    
    @Column(name="KEY20", length=64)
    public String getKey20() {
        return this.key20;
    }
    
    public void setKey20(String key20) {
        this.key20 = key20;
    }

    
    @Column(name="KEY21", length=64)
    public String getKey21() {
        return this.key21;
    }
    
    public void setKey21(String key21) {
        this.key21 = key21;
    }

    
    @Column(name="KEY22", length=64)
    public String getKey22() {
        return this.key22;
    }
    
    public void setKey22(String key22) {
        this.key22 = key22;
    }

    
    @Column(name="KEY23", length=512)
    public String getKey23() {
        return this.key23;
    }
    
    public void setKey23(String key23) {
        this.key23 = key23;
    }

    
    @Column(name="KEY24", length=512)
    public String getKey24() {
        return this.key24;
    }
    
    public void setKey24(String key24) {
        this.key24 = key24;
    }

    
    @Column(name="KEY25", length=512)
    public String getKey25() {
        return this.key25;
    }
    
    public void setKey25(String key25) {
        this.key25 = key25;
    }

    
    @Column(name="BLOB1")
    public byte[] getBlob1() {
        return this.blob1;
    }
    
    public void setBlob1(byte[] blob1) {
        this.blob1 = blob1;
    }

    
    @Column(name="BLOB2")
    public byte[] getBlob2() {
        return this.blob2;
    }
    
    public void setBlob2(byte[] blob2) {
        this.blob2 = blob2;
    }

    
    @Column(name="TMPRECORD")
    public String getTmprecord() {
        return this.tmprecord;
    }
    
    public void setTmprecord(String tmprecord) {
        this.tmprecord = tmprecord;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


