package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 5:36:45 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Audittrace generated by hbm2java
 */
@Entity
@Table(name="audittrace"
)
public class Audittrace  implements java.io.Serializable {


     private Long audittraceid;
     private String instancecode;
     private String institutecode;
     private String affectedkey;
     private Date createdtime;
     private String description;
     private String ip;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String newvalue;
     private String oldvalue;
     private String pagecode;
     private String remarks;
     private String taskcode;
     private String userrolecode;

    public Audittrace() {
    }

	
    public Audittrace(String instancecode, Date createdtime, String description, Date lastupdatedtime, String userrolecode) {
        this.instancecode = instancecode;
        this.createdtime = createdtime;
        this.description = description;
        this.lastupdatedtime = lastupdatedtime;
        this.userrolecode = userrolecode;
    }
    public Audittrace(String instancecode, String institutecode, String affectedkey, Date createdtime, String description, String ip, Date lastupdatedtime, String lastupdateduser, String newvalue, String oldvalue, String pagecode, String remarks, String taskcode, String userrolecode) {
       this.instancecode = instancecode;
       this.institutecode = institutecode;
       this.affectedkey = affectedkey;
       this.createdtime = createdtime;
       this.description = description;
       this.ip = ip;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.newvalue = newvalue;
       this.oldvalue = oldvalue;
       this.pagecode = pagecode;
       this.remarks = remarks;
       this.taskcode = taskcode;
       this.userrolecode = userrolecode;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AUDITTRACEID", unique=true, nullable=false)
    public Long getAudittraceid() {
        return this.audittraceid;
    }
    
    public void setAudittraceid(Long audittraceid) {
        this.audittraceid = audittraceid;
    }

    
    @Column(name="INSTANCECODE", nullable=false, length=16)
    public String getInstancecode() {
        return this.instancecode;
    }
    
    public void setInstancecode(String instancecode) {
        this.instancecode = instancecode;
    }

    
    @Column(name="INSTITUTECODE", length=16)
    public String getInstitutecode() {
        return this.institutecode;
    }
    
    public void setInstitutecode(String institutecode) {
        this.institutecode = institutecode;
    }

    
    @Column(name="AFFECTEDKEY", length=128)
    public String getAffectedkey() {
        return this.affectedkey;
    }
    
    public void setAffectedkey(String affectedkey) {
        this.affectedkey = affectedkey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="IP", length=64)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="NEWVALUE")
    public String getNewvalue() {
        return this.newvalue;
    }
    
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }

    
    @Column(name="OLDVALUE")
    public String getOldvalue() {
        return this.oldvalue;
    }
    
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }

    
    @Column(name="PAGECODE", length=16)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }

    
    @Column(name="REMARKS")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="TASKCODE", length=16)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    
    @Column(name="USERROLECODE", nullable=false)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }




}


