package com.epic.pos.posApp.Mapping;
// Generated Aug 13, 2019 3:05:22 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Complaintype generated by hbm2java
 */
@Entity
@Table(name="complaintype"
)
public class Complaintype  implements java.io.Serializable {


     private String complaintypecode;
     private Complaincategory complaincategory;
     private Status status;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Complaintype() {
    }

	
    public Complaintype(String complaintypecode, Complaincategory complaincategory, Status status, Date lastupdatedtime, Date createdtime) {
        this.complaintypecode = complaintypecode;
        this.complaincategory = complaincategory;
        this.status = status;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Complaintype(String complaintypecode, Complaincategory complaincategory, Status status, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.complaintypecode = complaintypecode;
       this.complaincategory = complaincategory;
       this.status = status;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id

    
    @Column(name="COMPLAINTYPECODE", unique=true, nullable=false, length=16)
    public String getComplaintypecode() {
        return this.complaintypecode;
    }
    
    public void setComplaintypecode(String complaintypecode) {
        this.complaintypecode = complaintypecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPLAINCATEGORY", nullable=false)
    public Complaincategory getComplaincategory() {
        return this.complaincategory;
    }
    
    public void setComplaincategory(Complaincategory complaincategory) {
        this.complaincategory = complaincategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


