package com.epic.pos.posApp.Mapping;
// Generated Sep 9, 2019 5:48:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Merchanttype generated by hbm2java
 */
@Entity
@Table(name="merchanttype"
)
public class Merchanttype  implements java.io.Serializable {


     private String merchanttypecode;
     private String description;

    public Merchanttype() {
    }

	
    public Merchanttype(String merchanttypecode) {
        this.merchanttypecode = merchanttypecode;
    }
    public Merchanttype(String merchanttypecode, String description) {
       this.merchanttypecode = merchanttypecode;
       this.description = description;
    }
   
     @Id

    
    @Column(name="MERCHANTTYPECODE", unique=true, nullable=false, length=16)
    public String getMerchanttypecode() {
        return this.merchanttypecode;
    }
    
    public void setMerchanttypecode(String merchanttypecode) {
        this.merchanttypecode = merchanttypecode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


