package com.epic.pos.posApp.Mapping;
// Generated Aug 20, 2019 6:41:35 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name="operation"
)
public class Operation  implements java.io.Serializable {


     private String operationcode;
     private Status status;
     private String description;
     private Short sortkey;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Operation() {
    }

	
    public Operation(String operationcode, Status status, Date lastupdatedtime, Date createdtime) {
        this.operationcode = operationcode;
        this.status = status;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Operation(String operationcode, Status status, String description, Short sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.operationcode = operationcode;
       this.status = status;
       this.description = description;
       this.sortkey = sortkey;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id

    
    @Column(name="OPERATIONCODE", unique=true, nullable=false, length=16)
    public String getOperationcode() {
        return this.operationcode;
    }
    
    public void setOperationcode(String operationcode) {
        this.operationcode = operationcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SORTKEY")
    public Short getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Short sortkey) {
        this.sortkey = sortkey;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


