package com.epic.pos.posApp.Mapping;
// Generated Sep 6, 2019 10:16:49 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Globaleprofile generated by hbm2java
 */
@Entity
@Table(name="globaleprofile"
)
public class Globaleprofile  implements java.io.Serializable {


     private Long id;
     private Application application;
     private Status status;
     private String key1;
     private String value1;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Globaleprofile() {
    }

	
    public Globaleprofile(Application application, String key1, Date lastupdatedtime, Date createdtime) {
        this.application = application;
        this.key1 = key1;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Globaleprofile(Application application, Status status, String key1, String value1, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.application = application;
       this.status = status;
       this.key1 = key1;
       this.value1 = value1;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPLICATION", nullable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="KEY1", nullable=false, length=64)
    public String getKey1() {
        return this.key1;
    }
    
    public void setKey1(String key1) {
        this.key1 = key1;
    }

    
    @Column(name="VALUE1", length=64)
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


