package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagetaskinstanceId generated by hbm2java
 */
@Embeddable
public class PagetaskinstanceId  implements java.io.Serializable {


     private int pagetask;
     private String instance;

    public PagetaskinstanceId() {
    }

    public PagetaskinstanceId(int pagetask, String instance) {
       this.pagetask = pagetask;
       this.instance = instance;
    }
   


    @Column(name="PAGETASK", nullable=false)
    public int getPagetask() {
        return this.pagetask;
    }
    
    public void setPagetask(int pagetask) {
        this.pagetask = pagetask;
    }


    @Column(name="INSTANCE", nullable=false, length=16)
    public String getInstance() {
        return this.instance;
    }
    
    public void setInstance(String instance) {
        this.instance = instance;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagetaskinstanceId) ) return false;
		 PagetaskinstanceId castOther = ( PagetaskinstanceId ) other; 
         
		 return (this.getPagetask()==castOther.getPagetask())
 && ( (this.getInstance()==castOther.getInstance()) || ( this.getInstance()!=null && castOther.getInstance()!=null && this.getInstance().equals(castOther.getInstance()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPagetask();
         result = 37 * result + ( getInstance() == null ? 0 : this.getInstance().hashCode() );
         return result;
   }   


}


