package com.epic.pos.posApp.Mapping;
// Generated Aug 23, 2019 11:46:40 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tempprofile generated by hbm2java
 */
@Entity
@Table(name="tempprofile"
    ,catalog="EHTMS"
)
public class Tempprofile  implements java.io.Serializable {


     private Long id;
     private Applicationversion applicationversion;
     private String key1;
     private String value1;

    public Tempprofile() {
    }

	
    public Tempprofile(Applicationversion applicationversion, String key1) {
        this.applicationversion = applicationversion;
        this.key1 = key1;
    }
    public Tempprofile(Applicationversion applicationversion, String key1, String value1) {
       this.applicationversion = applicationversion;
       this.key1 = key1;
       this.value1 = value1;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPLICATIONVERSION", nullable=false)
    public Applicationversion getApplicationversion() {
        return this.applicationversion;
    }
    
    public void setApplicationversion(Applicationversion applicationversion) {
        this.applicationversion = applicationversion;
    }

    
    @Column(name="KEY1", nullable=false, length=64)
    public String getKey1() {
        return this.key1;
    }
    
    public void setKey1(String key1) {
        this.key1 = key1;
    }

    
    @Column(name="VALUE1", length=64)
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }




}


