package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Devicemodel generated by hbm2java
 */
@Entity
@Table(name="devicemodel"
)
public class Devicemodel  implements java.io.Serializable {


     private Integer id;
     private Devicebrand devicebrand;
     private Status status;
     private String modelcode;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Applicationversion> applicationversions = new HashSet<Applicationversion>(0);
     private Set<Device> devices = new HashSet<Device>(0);

    public Devicemodel() {
    }

	
    public Devicemodel(Devicebrand devicebrand, Status status, String modelcode, Date lastupdatedtime, Date createdtime) {
        this.devicebrand = devicebrand;
        this.status = status;
        this.modelcode = modelcode;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Devicemodel(Devicebrand devicebrand, Status status, String modelcode, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Applicationversion> applicationversions, Set<Device> devices) {
       this.devicebrand = devicebrand;
       this.status = status;
       this.modelcode = modelcode;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.applicationversions = applicationversions;
       this.devices = devices;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEVICEBRAND", nullable=false)
    public Devicebrand getDevicebrand() {
        return this.devicebrand;
    }
    
    public void setDevicebrand(Devicebrand devicebrand) {
        this.devicebrand = devicebrand;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="MODELCODE", nullable=false, length=16)
    public String getModelcode() {
        return this.modelcode;
    }
    
    public void setModelcode(String modelcode) {
        this.modelcode = modelcode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devicemodel")
    public Set<Applicationversion> getApplicationversions() {
        return this.applicationversions;
    }
    
    public void setApplicationversions(Set<Applicationversion> applicationversions) {
        this.applicationversions = applicationversions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devicemodel")
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


