package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Devicebrand generated by hbm2java
 */
@Entity
@Table(name="devicebrand"
)
public class Devicebrand  implements java.io.Serializable {


     private Integer id;
     private Institute institute;
     private Status status;
     private String brandcode;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Devicemodel> devicemodels = new HashSet<Devicemodel>(0);

    public Devicebrand() {
    }

	
    public Devicebrand(Institute institute, Status status, String brandcode, Date lastupdatedtime, Date createdtime) {
        this.institute = institute;
        this.status = status;
        this.brandcode = brandcode;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Devicebrand(Institute institute, Status status, String brandcode, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Devicemodel> devicemodels) {
       this.institute = institute;
       this.status = status;
       this.brandcode = brandcode;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.devicemodels = devicemodels;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="INSTITUTE", nullable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="BRANDCODE", nullable=false, length=15)
    public String getBrandcode() {
        return this.brandcode;
    }
    
    public void setBrandcode(String brandcode) {
        this.brandcode = brandcode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devicebrand")
    public Set<Devicemodel> getDevicemodels() {
        return this.devicemodels;
    }
    
    public void setDevicemodels(Set<Devicemodel> devicemodels) {
        this.devicemodels = devicemodels;
    }




}


