package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Pagetaskinstitute generated by hbm2java
 */
@Entity
@Table(name="pagetaskinstitute"
)
public class Pagetaskinstitute  implements java.io.Serializable {


     private PagetaskinstituteId id;
     private Institute institute;
     private Pagetask pagetask;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Pagetaskinstitute() {
    }

	
    public Pagetaskinstitute(PagetaskinstituteId id, Institute institute, Pagetask pagetask, Date lastupdatedtime, Date createdtime) {
        this.id = id;
        this.institute = institute;
        this.pagetask = pagetask;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Pagetaskinstitute(PagetaskinstituteId id, Institute institute, Pagetask pagetask, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.institute = institute;
       this.pagetask = pagetask;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pagetask", column=@Column(name="PAGETASK", nullable=false) ),
        @AttributeOverride(name="institute", column=@Column(name="INSTITUTE", nullable=false) ) } )
    public PagetaskinstituteId getId() {
        return this.id;
    }
    
    public void setId(PagetaskinstituteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSTITUTE", nullable=false, insertable=false, updatable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGETASK", nullable=false, insertable=false, updatable=false)
    public Pagetask getPagetask() {
        return this.pagetask;
    }
    
    public void setPagetask(Pagetask pagetask) {
        this.pagetask = pagetask;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


