package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name="page"
)
public class Page  implements java.io.Serializable {


     private String pagecode;
     private Section section;
     private Status status;
     private String description;
     private Boolean dualauth;
     private Short sortkey;
     private String url;
     private Set<Pageinstitute> pageinstitutes = new HashSet<Pageinstitute>(0);
     private Set<Pagetask> pagetasks = new HashSet<Pagetask>(0);
     private Set<Pageinstance> pageinstances = new HashSet<Pageinstance>(0);
     private Set<Pagetaskuserrole> pagetaskuserroles = new HashSet<Pagetaskuserrole>(0);
     private Set<Pageuserrole> pageuserroles = new HashSet<Pageuserrole>(0);
     private Set<Tmpauthrec> tmpauthrecs = new HashSet<Tmpauthrec>(0);

    public Page() {
    }

	
    public Page(String pagecode, Section section, Status status, String description) {
        this.pagecode = pagecode;
        this.section = section;
        this.status = status;
        this.description = description;
    }
    public Page(String pagecode, Section section, Status status, String description, Boolean dualauth, Short sortkey, String url, Set<Pageinstitute> pageinstitutes, Set<Pagetask> pagetasks, Set<Pageinstance> pageinstances, Set<Pagetaskuserrole> pagetaskuserroles, Set<Pageuserrole> pageuserroles, Set<Tmpauthrec> tmpauthrecs) {
       this.pagecode = pagecode;
       this.section = section;
       this.status = status;
       this.description = description;
       this.dualauth = dualauth;
       this.sortkey = sortkey;
       this.url = url;
       this.pageinstitutes = pageinstitutes;
       this.pagetasks = pagetasks;
       this.pageinstances = pageinstances;
       this.pagetaskuserroles = pagetaskuserroles;
       this.pageuserroles = pageuserroles;
       this.tmpauthrecs = tmpauthrecs;
    }
   
     @Id

    
    @Column(name="PAGECODE", unique=true, nullable=false, length=16)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTION", nullable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="DUALAUTH")
    public Boolean getDualauth() {
        return this.dualauth;
    }
    
    public void setDualauth(Boolean dualauth) {
        this.dualauth = dualauth;
    }

    
    @Column(name="SORTKEY")
    public Short getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Short sortkey) {
        this.sortkey = sortkey;
    }

    
    @Column(name="URL", length=128)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pageinstitute> getPageinstitutes() {
        return this.pageinstitutes;
    }
    
    public void setPageinstitutes(Set<Pageinstitute> pageinstitutes) {
        this.pageinstitutes = pageinstitutes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pagetask> getPagetasks() {
        return this.pagetasks;
    }
    
    public void setPagetasks(Set<Pagetask> pagetasks) {
        this.pagetasks = pagetasks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pageinstance> getPageinstances() {
        return this.pageinstances;
    }
    
    public void setPageinstances(Set<Pageinstance> pageinstances) {
        this.pageinstances = pageinstances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pagetaskuserrole> getPagetaskuserroles() {
        return this.pagetaskuserroles;
    }
    
    public void setPagetaskuserroles(Set<Pagetaskuserrole> pagetaskuserroles) {
        this.pagetaskuserroles = pagetaskuserroles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Pageuserrole> getPageuserroles() {
        return this.pageuserroles;
    }
    
    public void setPageuserroles(Set<Pageuserrole> pageuserroles) {
        this.pageuserroles = pageuserroles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="page")
    public Set<Tmpauthrec> getTmpauthrecs() {
        return this.tmpauthrecs;
    }
    
    public void setTmpauthrecs(Set<Tmpauthrec> tmpauthrecs) {
        this.tmpauthrecs = tmpauthrecs;
    }




}


