package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Applicationversion generated by hbm2java
 */
@Entity
@Table(name="applicationversion"
)
public class Applicationversion  implements java.io.Serializable {


     private Long id;
     private String version;
     private Application application;
     private Devicemodel devicemodel;
     private Status status;
     private String description;
     private Date effectivedate;
     private String apkurl;
     private String scripturl;
     private String configurl;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Device> devices = new HashSet<Device>(0);

    public Applicationversion() {
    }

	
    public Applicationversion(Application application, Devicemodel devicemodel, String description, Date effectivedate, String configurl, Date lastupdatedtime, Date createdtime) {
        this.application = application;
        this.devicemodel = devicemodel;
        this.description = description;
        this.effectivedate = effectivedate;
        this.configurl = configurl;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Applicationversion(Application application, Devicemodel devicemodel, Status status, String description, Date effectivedate, String apkurl, String scripturl, String configurl, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Device> devices) {
       this.application = application;
       this.devicemodel = devicemodel;
       this.status = status;
       this.description = description;
       this.effectivedate = effectivedate;
       this.apkurl = apkurl;
       this.scripturl = scripturl;
       this.configurl = configurl;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.devices = devices;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }


    @Column(name="VERSION", nullable=false, length=16)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPLICATION", nullable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEVICEMODEL", nullable=false)
    public Devicemodel getDevicemodel() {
        return this.devicemodel;
    }
    
    public void setDevicemodel(Devicemodel devicemodel) {
        this.devicemodel = devicemodel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVEDATE", nullable=false, length=19)
    public Date getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }

    
    @Column(name="APKURL", length=256)
    public String getApkurl() {
        return this.apkurl;
    }
    
    public void setApkurl(String apkurl) {
        this.apkurl = apkurl;
    }

    
    @Column(name="SCRIPTURL", length=256)
    public String getScripturl() {
        return this.scripturl;
    }
    
    public void setScripturl(String scripturl) {
        this.scripturl = scripturl;
    }

    
    @Column(name="CONFIGURL", nullable=false, length=256)
    public String getConfigurl() {
        return this.configurl;
    }
    
    public void setConfigurl(String configurl) {
        this.configurl = configurl;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="applicationversion")
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


