package com.epic.pos.posApp.Mapping;
// Generated Aug 13, 2019 3:05:22 PM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Casehistory generated by hbm2java
 */
@Entity
@Table(name = "casehistory"
)
public class Casehistory implements java.io.Serializable {

    private Long id;
    private Customersupportcase customersupportcase;
    private Status status;
    private String remark;
    private String createduser;
    private Date createdtime;

    public Casehistory() {
    }

    public Casehistory(Customersupportcase customersupportcase, Status status, String remark, String createduser, Date createdtime) {
        this.customersupportcase = customersupportcase;
        this.status = status;
        this.remark = remark;
        this.createduser = createduser;
        this.createdtime = createdtime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMERSUPPORTCASE", nullable = false)
    public Customersupportcase getCustomersupportcase() {
        return this.customersupportcase;
    }

    public void setCustomersupportcase(Customersupportcase customersupportcase) {
        this.customersupportcase = customersupportcase;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS", nullable = false)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "REMARK", length = 256)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "CREATEDUSER", nullable = false, length = 64)
    public String getCreateduser() {
        return this.createduser;
    }

    public void setCreateduser(String createduser) {
        this.createduser = createduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", nullable = false, length = 19)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

}
