package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
)
public class Country  implements java.io.Serializable {


     private String countrycode;
     private Status status;
     private String alpha2code;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Province> provinces = new HashSet<Province>(0);
     private Set<Instance> instances = new HashSet<Instance>(0);
     private Set<Merchantcustomer> merchantcustomers = new HashSet<Merchantcustomer>(0);
     private Set<Merchant> merchants = new HashSet<Merchant>(0);

    public Country() {
    }

	
    public Country(String countrycode, Status status, Date lastupdatedtime, Date createdtime) {
        this.countrycode = countrycode;
        this.status = status;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Country(String countrycode, Status status, String alpha2code, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Province> provinces, Set<Instance> instances, Set<Merchantcustomer> merchantcustomers, Set<Merchant> merchants) {
       this.countrycode = countrycode;
       this.status = status;
       this.alpha2code = alpha2code;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.provinces = provinces;
       this.instances = instances;
       this.merchantcustomers = merchantcustomers;
       this.merchants = merchants;
    }
   
     @Id

    
    @Column(name="COUNTRYCODE", unique=true, nullable=false, length=16)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="ALPHA2CODE", length=16)
    public String getAlpha2code() {
        return this.alpha2code;
    }
    
    public void setAlpha2code(String alpha2code) {
        this.alpha2code = alpha2code;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Province> getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Set<Province> provinces) {
        this.provinces = provinces;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Instance> getInstances() {
        return this.instances;
    }
    
    public void setInstances(Set<Instance> instances) {
        this.instances = instances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Merchantcustomer> getMerchantcustomers() {
        return this.merchantcustomers;
    }
    
    public void setMerchantcustomers(Set<Merchantcustomer> merchantcustomers) {
        this.merchantcustomers = merchantcustomers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }




}


