package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Devicecategory generated by hbm2java
 */
@Entity
@Table(name="devicecategory"
)
public class Devicecategory  implements java.io.Serializable {


     private Integer id;
     private Institute institute;
     private Status status;
     private String devicecategorycode;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Date createdtime;
     private Set<Device> devices = new HashSet<Device>(0);

    public Devicecategory() {
    }

	
    public Devicecategory(Institute institute, Status status, String devicecategorycode, String description, Date lastupdatedtime, Date createdtime) {
        this.institute = institute;
        this.status = status;
        this.devicecategorycode = devicecategorycode;
        this.description = description;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }
    public Devicecategory(Institute institute, Status status, String devicecategorycode, String description, Date lastupdatedtime, String lastupdateduser, Date createdtime, Set<Device> devices) {
       this.institute = institute;
       this.status = status;
       this.devicecategorycode = devicecategorycode;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.createdtime = createdtime;
       this.devices = devices;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="INSTITUTE", nullable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="DEVICECATEGORYCODE", nullable=false, length=16)
    public String getDevicecategorycode() {
        return this.devicecategorycode;
    }
    
    public void setDevicecategorycode(String devicecategorycode) {
        this.devicecategorycode = devicecategorycode;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devicecategory")
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


