package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PageinstituteId generated by hbm2java
 */
@Embeddable
public class PageinstituteId  implements java.io.Serializable {


     private String page;
     private int institute;

    public PageinstituteId() {
    }

    public PageinstituteId(String page, int institute) {
       this.page = page;
       this.institute = institute;
    }
   


    @Column(name="PAGE", nullable=false, length=16)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }


    @Column(name="INSTITUTE", nullable=false)
    public int getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(int institute) {
        this.institute = institute;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PageinstituteId) ) return false;
		 PageinstituteId castOther = ( PageinstituteId ) other; 
         
		 return ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) )
 && (this.getInstitute()==castOther.getInstitute());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         result = 37 * result + this.getInstitute();
         return result;
   }   


}


