package com.epic.pos.posApp.Mapping;
// Generated Jul 30, 2019 11:58:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PageinstanceId generated by hbm2java
 */
@Embeddable
public class PageinstanceId  implements java.io.Serializable {


     private String page;
     private String instance;

    public PageinstanceId() {
    }

    public PageinstanceId(String page, String instance) {
       this.page = page;
       this.instance = instance;
    }
   


    @Column(name="PAGE", nullable=false, length=16)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }


    @Column(name="INSTANCE", nullable=false, length=16)
    public String getInstance() {
        return this.instance;
    }
    
    public void setInstance(String instance) {
        this.instance = instance;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PageinstanceId) ) return false;
		 PageinstanceId castOther = ( PageinstanceId ) other; 
         
		 return ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) )
 && ( (this.getInstance()==castOther.getInstance()) || ( this.getInstance()!=null && castOther.getInstance()!=null && this.getInstance().equals(castOther.getInstance()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         result = 37 * result + ( getInstance() == null ? 0 : this.getInstance().hashCode() );
         return result;
   }   


}


